name: release

on:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Released by GitHub Actions
          draft: false
          prerelease: false
      - run: echo ${{ steps.create_release.outputs.upload_url }} > upload_url.txt
      - uses: actions/upload-artifact@v1
        with:
          name: upload_url
          path: upload_url.txt
  build:
    needs: prepare
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/download-artifact@v1
        with:
          name: upload_url
          path: .
      - run: ::set-env name=UPLOAD_URL::$(cat upload_url.txt)
      - uses: allenevans/set-env@v1.0.0
        with:
          UPLOAD_URL: $(cat upload_url.txt)
      - run: echo ${UPLOAD_URL}
      - run: echo {{ UPLOAD_URL }}
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     UPLOAD_URL: ${{ UPLOAD_URL }}
      #   with:
      #     upload_url: ${{ UPLOAD_URL }}
      #     asset_path: target/release/pwgen
      #     asset_name: pwgen.${{ runner.os }}
      #     asset_content_type: application/octet-stream
